syntax = "proto3";

package ethereum.eth.v1alpha1;

import "proto/eth/ext/options.proto";
import "proto/engine/v1/electra.proto";

option go_package = "github.com/OffchainLabs/prysm/v6/proto/prysm/v1alpha1;eth";
option java_multiple_files = true;
option java_outer_classname = "ExecutionChunkProto";
option java_package = "org.ethereum.eth.v1alpha1";
option php_namespace = "Ethereum\\Eth\\v1alpha1";

message ExecutionChunkHeader {
  // TODO
}

message ExecutionChunk {
  // TODO
  ExecutionChunkHeader chunk_header = 1;
  repeated bytes transactions = 2 [
    (ethereum.eth.ext.ssz_size) = "?,?",
    (ethereum.eth.ext.ssz_max) = "1048576,1073741824"
  ];
  ethereum.engine.v1.ExecutionRequests execution_requests = 3;
}
